"""Initial schema

Revision ID: 4f95c173f1d9
Revises: 
Create Date: 2021-04-23 01:02:40.157049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f95c173f1d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('owner', 'reason', name='unique_key')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.String(length=80), nullable=False),
    sa.Column('quote', sa.String(length=200), nullable=False),
    sa.Column('speaker', sa.String(length=50), nullable=False),
    sa.Column('quote_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('voter', sa.String(length=200), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('quote')
    op.drop_table('api_key')
    # ### end Alembic commands ###
