"""empty message

Revision ID: d2b650b4745d
Revises: 30b25da0eff8
Create Date: 2017-08-27 01:25:12.539846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2b650b4745d'
down_revision = '30b25da0eff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quoteTime', new_column_name='submit_time')
    op.add_column('quote', sa.Column('quote_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submit_time', new_column_name='quoteTime')
    op.drop_column('quote', 'quote_date')
    # ### end Alembic commands ###
